#!/bin/bash

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )" 

cd $SCRIPT_DIR

echo "$1 changes: "

CHANGES=$(diff "data/$1.txt" "olddata/$1.txt")

[ -z "$CHANGES" ] && echo "no changes for $1" && exit 1

echo "$CHANGES"
